{% set name = "hydrostats" %}
{% set version = "0.76" %}
{% set sha256 = "9715623b38d2d94d5067144d944fbdae7c82d9e18242eaa842f015f7cca89bf3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  

requirements:
  host:
    - pip
    - python
  run:
    - python
    - numpy
    - scipy
    - numba
    - pandas
    - matplotlib
    - hydroerr

test:
  imports:
    - hydrostats
    - hydrostats.analyze
    - hydrostats.data
    - hydrostats.ens_metrics
    - hydrostats.metrics
    - hydrostats.visual

about:
  home: https://github.com/BYU-Hydroinformatics/Hydrostats
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'Tools for use in comparison studies, specifically for use in the field of hydrology'
  doc_url: https://byu-hydroinformatics.github.io/Hydrostats/
  dev_url: https://github.com/BYU-Hydroinformatics/Hydrostats
  
extra:
  recipe-maintainers:
    - waderoberts123
