travis:
  secure:
    BINSTAR_TOKEN: sBGfoWdFsORsf5kZGed2Stvrl9vD7Oaxpb7N5sXbkMl4Re8n+Xc0cPyazrPpbw9qlQvv7gMRYeFV0Ov+NO7prh93Ifv/jkz5m7ZKJF7thSMcRrhKE1JkBXzytWcccYIVK8SLt0MQmggBzQJf+XhXDo/ITMSne4wnoNH9DKkNctUNHVu2sji7RfM8PfwgEdL23QbiNkVxOlZ/mvlCgUANe43zthEfbVvYGbJz2+Anv2XcXAp0hkTFHgJaLLegFoRVaOeZpLTKPWRtfugZopo9SxcEr7lxkN1LbLr5k0Qf8MKmodMBSTsp77tjUdNK97If7sdk4pJxCL1iQdLd5qUwzMbhGViSUWRbt30FV55kqO/uqlONa7pouBYhaGZkurJbCUheXeRaezfKiAUZGBGgIXLI4nU/h/pw3wN5SSPZrOywfXKwc+UBww2gm59VQ6KsOAriQ3CSjTdNgcyA8S95SjlRJczp0A4R0k58wyNj+H68zk6o+2QoJJ7hE9hcy0gw0bv2g1gxNTVRiHOYzX2H1tRaTyn2xgOFYKBd2sivyAiSbNmygWDd3tdMNoSjE1kRcnafgH7k1L2Gb68DJnczdZwfdeN+mgZ+HqSoU8ldAtlMcXSvA0f7njNK/sUyMU1cKq0rwR6AbcWTMdT2s4RXNid6g2Pdg+rAPw1mtleQ4/Y=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
